lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/app/config/jwt/private.pem'
    public_key:       '%kernel.project_dir%/app/config/jwt/public.pem'
    pass_phrase:      'simplebudgetpewpew'
    token_ttl:        3600